/**
 * zenpix-wasm — browser-side AVIF encoder
 *
 * Usage (ESM, bundler or native module):
 *
 *   import { createAvifEncoder } from 'zenpix-wasm';
 *
 *   const enc = await createAvifEncoder();
 *   const avif = enc.encode(rgbaPixels, width, height, { quality: 60, speed: 10 });
 *   if (avif) {
 *     const blob = new Blob([avif], { type: 'image/avif' });
 *     // ...
 *   }
 *   enc.dispose();   // free WASM heap resources (optional — GC will clean up)
 *
 * @module
 */

/** Emscripten module factory type (generated by avif.js). */
type EmscriptenFactory = () => Promise<EmscriptenModule>;

interface EmscriptenModule {
  ccall(
    name: string,
    returnType: string | null,
    argTypes: string[],
    args: unknown[]
  ): unknown;
  HEAPU8: Uint8Array;
  _malloc(size: number): number;
  _free(ptr: number): void;
  _avif_encode(
    pixels: number,
    width: number,
    height: number,
    channels: number,
    quality: number,
    speed: number
  ): number;
  _avif_get_out_size(): number;
  _avif_free_output(ptr: number): void;
  _avif_version(): number;
}

/** Options for AVIF encoding. */
export interface AvifEncodeOptions {
  /**
   * Encode quality, 0–100 (higher = better quality, larger file).
   * @default 60
   */
  quality?: number;
  /**
   * Encoder speed/effort, 0–10 (10 = fastest, lowest quality).
   * @default 10
   */
  speed?: number;
}

/** Handle returned by {@link createAvifEncoder}. */
export interface AvifEncoder {
  /**
   * Encode raw pixel data to AVIF.
   *
   * @param pixels - Raw pixel bytes: tightly-packed row-major RGB or RGBA (8-bit/channel).
   * @param width  - Image width in pixels.
   * @param height - Image height in pixels.
   * @param opts   - Encoding options.
   * @returns Uint8Array containing the AVIF bitstream, or `null` on failure.
   */
  encode(
    pixels: Uint8Array,
    width: number,
    height: number,
    opts?: AvifEncodeOptions
  ): Uint8Array | null;

  /**
   * libavif version string (e.g. `"1.4.1"`).
   */
  readonly version: string;

  /** Free persistent WASM heap allocations (no-op if nothing to free). */
  dispose(): void;
}

/**
 * Load the WASM module and return an {@link AvifEncoder} instance.
 *
 * @param wasmUrl - Optional URL to `avif.wasm`.  Defaults to `./avif.wasm`
 *                  (same directory as the JS bundle).
 */
export async function createAvifEncoder(wasmUrl?: string): Promise<AvifEncoder> {
  // Dynamic import so bundlers can split the factory into a separate chunk.
  // The factory is an ES module default export produced by Emscripten with
  // MODULARIZE=1 + EXPORT_ES6=1.
  const factoryModule = await import(/* @vite-ignore */ '../dist/avif.js') as {
    default: EmscriptenFactory;
  };

  const options: Record<string, unknown> = {};
  if (wasmUrl) {
    options.locateFile = (file: string) => (file.endsWith('.wasm') ? wasmUrl : file);
  }

  const Module = await factoryModule.default(options as never);

  // Read the libavif version string from WASM memory.
  const versionPtr = Module.ccall('avif_version', 'number', [], []) as number;
  const version = readCString(Module.HEAPU8, versionPtr);

  return {
    version,

    encode(
      pixels: Uint8Array,
      width: number,
      height: number,
      opts: AvifEncodeOptions = {}
    ): Uint8Array | null {
      const quality = opts.quality ?? 60;
      const speed = opts.speed ?? 10;

      if (
        quality < 0 || quality > 100 ||
        speed  < 0 || speed  > 10
      ) {
        return null;
      }

      const channels = pixels.length / (width * height);
      if (channels !== 3 && channels !== 4) return null;

      // Copy pixel data into WASM heap.
      const inputPtr = Module._malloc(pixels.length);
      if (!inputPtr) return null;
      Module.HEAPU8.set(pixels, inputPtr);

      // Call the encoder.
      const outPtr = Module._avif_encode(
        inputPtr,
        width,
        height,
        channels,
        quality,
        speed
      );
      Module._free(inputPtr);

      if (!outPtr) return null;

      // Copy output bytes out of WASM heap before freeing.
      const outSize = Module._avif_get_out_size();
      const result = Module.HEAPU8.slice(outPtr, outPtr + outSize);
      Module._avif_free_output(outPtr);

      return result;
    },

    dispose(): void {
      // Nothing to dispose — Module owns its own heap.
    },
  };
}

/** Read a null-terminated C string from a Uint8Array at the given byte offset. */
function readCString(heap: Uint8Array, ptr: number): string {
  let end = ptr;
  while (heap[end] !== 0) end++;
  return new TextDecoder().decode(heap.subarray(ptr, end));
}
